### PR TITLE
Apply fix for aot issue

### PR DESCRIPTION
**Pull request by wermerb**
This PR will fix the following error #51: 

`ERROR in Error: Error encountered resolving symbol values statically. Calling function 'SortablejsModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol ....
`

### CODE REVIEW

**Comment by smnbbrv** [comment]
hi @wermerb 

thanks for your effort.

I don't want to be one of those guys and I understand that most likely you used auto-beautify etc, however the amount of changes for such a small thing is too high and it is really hard to review that.

Could you, please, change it in a way that only the real changes are applied without changing the whole `sortablejs.directive.ts` structure?

**Comment by wermerb** [comment]
Hi @smnbbrv !

Sure np give me a sec :)

**Comment by smnbbrv** [comment]
Thank you! Looks fine. I will also apply a fix for another issue and release a version within 10 mins

**Comment by wermerb** [comment]
Cheers happy to help :+1:

**Pull request merged**
