### PR TITLE
disableBinding option

### PR DESCRIPTION
**Pull request by lbertenasco**

### CODE REVIEW

**Comment by lbertenasco** [comment]
Hi @smnbbrv, 

We just found a bug on Drag & drop between two lists.

If we set the property `disableBinding` to true it works just fine.

The issue was that `this.onremove` was null on `overridenOptions.onRemove`

**Comment by smnbbrv** [comment]
Hi @lbertenasco 

the `onremove` is kinda a dirty hack. The purpose of one before was that it was outside of the component (before it was moved in), so it was global and not depending on the list.

Now it is of course always null because the new item is added to another list and the target list gets the onremove function, although the one that loses an item should get one.

What was the reason of making it a member property instead of simple `let`? AOT? Would making it a static property solve the issue (if it is a static property it would still work fine)?

**Comment by smnbbrv** [comment]
@lbertenasco sorry for so complicated text, cannot understand it by myself when re-read it :) So, the idea of `onremove` is to be global and single for the whole app exactly for drag&drop between the lists. When you moved it inside of the component it does not work anymore. We either should move it back to be a separate variable or make it a static property on `SortablejsDirective` which is the same thing.

This will fix the issue without any additional parameter and actually this is how it is supposed to be.

Do you see some problems with this?

**Comment by lbertenasco** [comment]
hi @smnbbrv , I think there will be an issue with the `event` since it's specific to the list elements.
```
  this.onremove = (item: any) => {
    if (this.isItemsFormArray) {
        this.items.insert(*event.newIndex*, item);
    } else {
        this.items.splice(*event.newIndex*, 0, item);
    }
  };
```
I'm not sure on how to fix this, I'll try to find a solution on my free time.

Also I think the user should be able to handle this changes on his end if desired.
That's why I added the `disableBinding` option which should be *explained on the README.md*

**Comment by smnbbrv** [comment]
it was working before :) as long as it is an arrow function it catches `this` of the current context (the sortable where it gets added) and remembers it until the element of another sortable where it gets deleted actually calls it. If it is not an AOT thing I will return it then and let you know the version to test.

About `disableBinding` - it is already possible to do it from the user side - just pass nothing (or null or whatsoever) to the `[sortablejs]`, and this is already written in the README

**Comment by smnbbrv** [comment]
@lbertenasco try angular-sortablejs@2.0.0-1

**Comment by lbertenasco** [comment]
@smnbbrv On `angular-sortablejs@2.0.0-1` I get:
`Uncaught Error: Unexpected value 'undefined' exported by the module 'SortablejsModule'`

Ok, I think I've got a clearer picture now. I'm going to test some things and get back to you.

**Comment by smnbbrv** [comment]
@lbertenasco I pushed the changes etc, so you can have a look at updated things...

and that actually looks like https://github.com/SortableJS/angular-sortablejs/issues/34

**Comment by smnbbrv** [comment]
I think I close this pull request, feel free to make a new one 👍

**Pull request closed without merging**
