### PR TITLE
package updates and build fix

### PR DESCRIPTION
**Pull request by lbertenasco**

### CODE REVIEW

**Comment by smnbbrv** [comment]
Hi @lbertenasco 

thank you for pull request  👍 . I am thinking to merge it next week to release it under 2.0.0 (I also want to make some breaking changes).

Just FYI

**Comment by smnbbrv** [comment]
@lbertenasco 

do you think does is it supposed to fix #34 as well?

**Comment by lbertenasco** [comment]
Hi @smnbbr, thanks.

About the AoT Rollup issue I'm not sure, I would need to check with a sample repo.
But it might work.

**Comment by smnbbrv** [comment]
hi @lbertenasco 

thank you for contribution.

I moved sortablejs to the peerDependencies, so you can try it now with your projects with

```sh
npm install --save sortablejs && npm install --save angular-sortablejs@2.0.0-0
```

Please let me know if this works so we can make a stable 2.0.0

**Pull request merged**
