### PR TITLE
SortablejsService.onremove function

### PR DESCRIPTION
**Pull request by lbertenasco**

### CODE REVIEW

**Comment by smnbbrv** [comment]
looks good so far. Could not imagine why AOT cannot understand simple closure... Try the 2.0.0 and I think we are done ;) Good job!

**Comment by lbertenasco** [comment]
AoT is a world of its own... and it's a mess some times.

on `v2.0.0` I get
`Uncaught Error: Unexpected value 'undefined' exported by the module 'SortablejsModule'`

What version of `node` are you using to compile? mine is `v6.9.1`

Because It works fine if I clone the repo and build it locally or use my `ap-angular-sortablejs` package.

**Comment by smnbbrv** [comment]
hem... v7.8.0

**Comment by lbertenasco** [comment]
You can also try to clean your packages and installing everything again with:
`rm -r node_modules && npm i`
But I can't seem to find the actual issue here :confused:

**Comment by smnbbrv** [comment]
done, you can try with @2.0.1-0

**Comment by lbertenasco** [comment]
Still the same error, I'll check if I can quickly fix it on my end.
I'll ping you if I get anything.

**Comment by smnbbrv** [comment]
I think I found the reason... Give me 5 minutes

**Comment by lbertenasco** [comment]
Ah, the `onremove` function is still on the `SortablejsDirective`!

If you remove it, it should be ok again.

**Comment by smnbbrv** [comment]
nope don't think so. I think the reason was in a circular dependency (module was imported in a directive and directive was imported in the module) that is why the race condition occurs and module sometimes imports a directive which is at the moment undefined

Try 2.0.1-1 now. Also removed the variable btw

**Comment by lbertenasco** [comment]
Perfect! Thanks a lot :)

`v2.0.1-1` It's working fine

**Comment by smnbbrv** [comment]
ok, then 2.0.1 is there as well. Thank you very much for your help! 👍 I really appreciate that

**Comment by lbertenasco** [comment]
No problem, happy to help :smile: 

I'll let you know if we encounter any other issues

**Pull request merged**
