### PR TITLE
Bind events outside Angular zone by default

### PR DESCRIPTION
**Pull request by jeevandark**
Hi,

This will help me with my current project - if you accept it please let me know when can it be availble via the NPM package as the latest version...  Thanks!

### CODE REVIEW

**Comment by smnbbrv** [comment]
Hi @jeevandark,

The change could lead to some side effects, that's why I have to ask that (don't take as offence please): did you already test the solution?  Does it make sense to merge it and make the prerelease version first that we can test it for some time?

**Comment by jeevandark** [comment]
Hi @smnbbrv  :)

This helped me in fixing the problem in our project (staggering UI in a large component). As far as I have seen this causes no side effects, and I am quite sure about it. 
Of course you can make a pre-release version first (I'm not exactly sure what you mean by that in npm terms), and I'll be happy to help with that in any way I can.

I also wouldn't mind changing the default to true (effectively cancelling any change), or renaming the parameter to [runOutsideAngular] and setting the default to false (which is essentially the same thing) - what ever you want, as long as I can have the option of affecting the runtime in this way...

It's your call, of course.

**Comment by smnbbrv** [comment]
@jeevandark I think we can try it, I spent some time to find out possible problems and did not find any. Let's see if other guys will have something, but I see no problem merging it

**Comment by smnbbrv** [comment]
@jeevandark 1.1.0 should contain the changes. Please check. Thank you for your time and assistance! 👍

**Pull request merged**
